// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && with_ebpf

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	ICMPEchoReplyMapIcmpEchoReplyControl                      = "icmp_echo_reply_control"
	ICMPEchoReplyMapIcmpEchoReplyStats                        = "icmp_echo_reply_stats"
	ICMPEchoReplyProgSingEbpfIcmpEchoReplyLocalReplyEthernet  = "sing_ebpf_icmp_echo_reply_local_reply_ethernet"
	ICMPEchoReplyProgSingEbpfIcmpEchoReplyLocalReplyRawIp     = "sing_ebpf_icmp_echo_reply_local_reply_raw_ip"
	ICMPEchoReplyProgSingEbpfIcmpEchoReplySharedReplyEthernet = "sing_ebpf_icmp_echo_reply_shared_reply_ethernet"
	ICMPEchoReplyProgSingEbpfIcmpEchoReplySharedReplyRawIp    = "sing_ebpf_icmp_echo_reply_shared_reply_raw_ip"
)

// LoadICMPEchoReply returns the embedded CollectionSpec for ICMPEchoReply.
func LoadICMPEchoReply() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ICMPEchoReplyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ICMPEchoReply: %w", err)
	}

	return spec, err
}

// LoadICMPEchoReplyObjects loads ICMPEchoReply and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ICMPEchoReplyObjects
//	*ICMPEchoReplyPrograms
//	*ICMPEchoReplyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadICMPEchoReplyObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadICMPEchoReply()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ICMPEchoReplySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ICMPEchoReplySpecs struct {
	ICMPEchoReplyProgramSpecs
	ICMPEchoReplyMapSpecs
	ICMPEchoReplyVariableSpecs
}

// ICMPEchoReplyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ICMPEchoReplyProgramSpecs struct {
	SingEbpfIcmpEchoReplyLocalReplyEthernet  *ebpf.ProgramSpec `ebpf:"sing_ebpf_icmp_echo_reply_local_reply_ethernet"`
	SingEbpfIcmpEchoReplyLocalReplyRawIp     *ebpf.ProgramSpec `ebpf:"sing_ebpf_icmp_echo_reply_local_reply_raw_ip"`
	SingEbpfIcmpEchoReplySharedReplyEthernet *ebpf.ProgramSpec `ebpf:"sing_ebpf_icmp_echo_reply_shared_reply_ethernet"`
	SingEbpfIcmpEchoReplySharedReplyRawIp    *ebpf.ProgramSpec `ebpf:"sing_ebpf_icmp_echo_reply_shared_reply_raw_ip"`
}

// ICMPEchoReplyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ICMPEchoReplyMapSpecs struct {
	IcmpEchoReplyControl *ebpf.MapSpec `ebpf:"icmp_echo_reply_control"`
	IcmpEchoReplyStats   *ebpf.MapSpec `ebpf:"icmp_echo_reply_stats"`
}

// ICMPEchoReplyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ICMPEchoReplyVariableSpecs struct {
}

// ICMPEchoReplyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadICMPEchoReplyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ICMPEchoReplyObjects struct {
	ICMPEchoReplyPrograms
	ICMPEchoReplyMaps
	ICMPEchoReplyVariables
}

func (o *ICMPEchoReplyObjects) Close() error {
	return _ICMPEchoReplyClose(
		&o.ICMPEchoReplyPrograms,
		&o.ICMPEchoReplyMaps,
	)
}

// ICMPEchoReplyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadICMPEchoReplyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ICMPEchoReplyMaps struct {
	IcmpEchoReplyControl *ebpf.Map `ebpf:"icmp_echo_reply_control"`
	IcmpEchoReplyStats   *ebpf.Map `ebpf:"icmp_echo_reply_stats"`
}

func (m *ICMPEchoReplyMaps) Close() error {
	return _ICMPEchoReplyClose(
		m.IcmpEchoReplyControl,
		m.IcmpEchoReplyStats,
	)
}

// ICMPEchoReplyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadICMPEchoReplyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ICMPEchoReplyVariables struct {
}

// ICMPEchoReplyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadICMPEchoReplyObjects or ebpf.CollectionSpec.LoadAndAssign.
type ICMPEchoReplyPrograms struct {
	SingEbpfIcmpEchoReplyLocalReplyEthernet  *ebpf.Program `ebpf:"sing_ebpf_icmp_echo_reply_local_reply_ethernet"`
	SingEbpfIcmpEchoReplyLocalReplyRawIp     *ebpf.Program `ebpf:"sing_ebpf_icmp_echo_reply_local_reply_raw_ip"`
	SingEbpfIcmpEchoReplySharedReplyEthernet *ebpf.Program `ebpf:"sing_ebpf_icmp_echo_reply_shared_reply_ethernet"`
	SingEbpfIcmpEchoReplySharedReplyRawIp    *ebpf.Program `ebpf:"sing_ebpf_icmp_echo_reply_shared_reply_raw_ip"`
}

func (p *ICMPEchoReplyPrograms) Close() error {
	return _ICMPEchoReplyClose(
		p.SingEbpfIcmpEchoReplyLocalReplyEthernet,
		p.SingEbpfIcmpEchoReplyLocalReplyRawIp,
		p.SingEbpfIcmpEchoReplySharedReplyEthernet,
		p.SingEbpfIcmpEchoReplySharedReplyRawIp,
	)
}

func _ICMPEchoReplyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed icmp_echo_reply_bpfel.o
var _ICMPEchoReplyBytes []byte
